# Generated by Django 4.2.27 on 2026-08-30 11:34

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PLANNED', 'Planifie'), ('ACTIVE', 'Actif'), ('ON_HOLD', 'En pause'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=24)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Prive'), ('TEAM', 'Equipe'), ('WORKSPACE', 'Workspace')], default='WORKSPACE', max_length=16)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('progress_mode', models.CharField(default='AUTO', max_length=16)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('partners', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='members.member')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='projects.project')),
                ('responsible_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='members.member')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_projects', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('planned_budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_budget_categories', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_PROGRESS', 'En cours'), ('COMPLETED', 'Termine'), ('DELAYED', 'En retard')], default='PENDING', max_length=24)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_milestones', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROJECT_MANAGER', 'Responsable projet'), ('MEMBER', 'Membre'), ('FINANCE', 'Finance'), ('OBSERVER', 'Observateur')], default='MEMBER', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='members.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_expense_id', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_allocations', to='projects.projectbudgetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_allocations', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expense_allocations', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(blank=True, upload_to='project-documents/')),
                ('document_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('project.task_overdue', 'Tache en retard'), ('project.deadline_near', 'Echeance proche'), ('project.budget_near_limit', 'Budget proche limite'), ('project.budget_exceeded', 'Budget depasse'), ('project.milestone_delayed', 'Jalon en retard')], max_length=64)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Eleve'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=16)),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_alerts', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Basse'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Haute'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=24)),
                ('status', models.CharField(choices=[('TODO', 'A faire'), ('IN_PROGRESS', 'En cours'), ('BLOCKED', 'Bloque'), ('DONE', 'Termine'), ('CANCELLED', 'Annule')], default='TODO', max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to='members.member')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependents', to='projects.projecttask')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.projectmilestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'project'], name='projects_pr_workspa_1cb201_idx'), models.Index(fields=['workspace', 'assignee'], name='projects_pr_workspa_d8ae29_idx'), models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_3a8ac1_idx'), models.Index(fields=['workspace', 'due_date'], name='projects_pr_workspa_98551a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('target', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non demarre'), ('IN_PROGRESS', 'En cours'), ('ACHIEVED', 'Atteint'), ('AT_RISK', 'A risque'), ('CANCELLED', 'Annule')], default='NOT_STARTED', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_items', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_objectives', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'project'], name='projects_pr_workspa_2d6b9e_idx'), models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_f752b9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['workspace', 'project'], name='projects_pr_workspa_ff294e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['workspace', 'due_date'], name='projects_pr_workspa_74cfe6_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmilestone',
            index=models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_6466a2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['workspace', 'project'], name='projects_pr_workspa_8c9c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['workspace', 'member'], name='projects_pr_workspa_285907_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['workspace', 'role'], name='projects_pr_workspa_cd69e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(fields=('project', 'member'), name='uniq_project_member'),
        ),
        migrations.AddIndex(
            model_name='projectexpenseallocation',
            index=models.Index(fields=['workspace', 'project', 'spent_at'], name='projects_pr_workspa_bbdab2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectexpenseallocation',
            index=models.Index(fields=['workspace', 'external_expense_id'], name='projects_pr_workspa_76a2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='projectdocument',
            index=models.Index(fields=['workspace', 'project', '-created_at'], name='projects_pr_workspa_acbc69_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['workspace', 'project', '-created_at'], name='projects_pr_workspa_c43e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectbudgetcategory',
            index=models.Index(fields=['workspace', 'project'], name='projects_pr_workspa_d59ec0_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectbudgetcategory',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_project_budget_category_name'),
        ),
        migrations.AddIndex(
            model_name='projectalert',
            index=models.Index(fields=['workspace', 'project', 'is_resolved'], name='projects_pr_workspa_05262b_idx'),
        ),
        migrations.AddIndex(
            model_name='projectalert',
            index=models.Index(fields=['workspace', 'severity', '-created_at'], name='projects_pr_workspa_41d727_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['workspace', 'project', '-created_at'], name='projects_pr_workspa_e71eca_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['action', '-created_at'], name='projects_pr_action_dd7736_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'status'], name='projects_pr_workspa_944c68_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'priority'], name='projects_pr_workspa_212e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'owner'], name='projects_pr_workspa_624aea_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'end_date'], name='projects_pr_workspa_e984ca_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'start_date'], name='projects_pr_workspa_b85ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['workspace', 'created_at'], name='projects_pr_workspa_0e1a62_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='uniq_project_workspace_code'),
        ),
    ]
