# Generated by Codex on 2026-09-04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def mark_existing_users_verified(apps, _schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email_verified_at__isnull=True).update(email_verified_at=django.utils.timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOTPVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purpose", models.CharField(choices=[("registration", "Inscription")], default="registration", max_length=32)),
                ("channel", models.CharField(choices=[("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp")], default="email", max_length=24)),
                ("destination", models.CharField(max_length=254)),
                ("code_hash", models.CharField(max_length=96)),
                ("zavu_message_id", models.CharField(blank=True, max_length=120)),
                ("expires_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="otp_verifications", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name="userotpverification",
            index=models.Index(fields=["user", "purpose", "verified_at"], name="users_usero_user_id_206cb5_idx"),
        ),
        migrations.AddIndex(
            model_name="userotpverification",
            index=models.Index(fields=["destination", "purpose", "created_at"], name="users_usero_destina_f83448_idx"),
        ),
        migrations.RunPython(mark_existing_users_verified, migrations.RunPython.noop),
    ]
