# Generated by Django 4.2.27 on 2026-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userotpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotpverification',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('sms_oneway', 'SMS one way'), ('whatsapp', 'WhatsApp')], default='email', max_length=24),
        ),
    ]
