# Generated by Django 4.2.27 on 2026-08-30 11:53

import apps.events.statuses
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '__first__'),
        ('payments', '0002_financialadjustment_paymentdocument_and_more'),
        ('projects', '0001_initial'),
        ('members', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('MEETING', 'Reunion'), ('GENERAL_ASSEMBLY', 'Assemblee generale'), ('TRAINING', 'Formation'), ('CONFERENCE', 'Conference'), ('SEMINAR', 'Seminaire'), ('WORKSHOP', 'Atelier'), ('CEREMONY', 'Ceremonie'), ('FUNDRAISING', 'Collecte de fonds'), ('SOCIAL', 'Social'), ('COMMUNITY', 'Communautaire'), ('SPORT', 'Sport'), ('CULTURAL', 'Culturel'), ('OTHER', 'Autre')], default='OTHER', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PLANNED', 'Planifie'), ('REGISTRATION_OPEN', 'Inscriptions ouvertes'), ('REGISTRATION_CLOSED', 'Inscriptions fermees'), ('ONGOING', 'En cours'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule'), ('POSTPONED', 'Reporte'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=24)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Prive'), ('MEMBERS_ONLY', 'Membres uniquement'), ('WORKSPACE', 'Workspace'), ('PUBLIC', 'Public')], default='WORKSPACE', max_length=16)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64)),
                ('location_type', models.CharField(choices=[('PHYSICAL', 'Physique'), ('ONLINE', 'En ligne'), ('HYBRID', 'Hybride')], default='PHYSICAL', max_length=16)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('address', models.CharField(blank=True, max_length=220)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='CI', max_length=2)),
                ('online_url', models.URLField(blank=True)),
                ('online_platform', models.CharField(blank=True, max_length=80)),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('recurrence', models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('yearly', 'Annuelle')], default='none', max_length=16)),
                ('reminder_offsets', models.JSONField(blank=True, default=apps.events.statuses.default_reminder_offsets)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_events', to='members.member')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='projects.project')),
                ('responsible_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to='members.member')),
                ('responsible_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invite'), ('REGISTERED', 'Inscrit'), ('CONFIRMED', 'Confirme'), ('WAITLISTED', "Liste d'attente"), ('DECLINED', 'Refuse'), ('ATTENDED', 'Present'), ('ABSENT', 'Absent'), ('CANCELLED', 'Annule')], default='INVITED', max_length=24)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('qr_code', models.CharField(blank=True, max_length=120)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('INVITED', 'Invite'), ('REGISTERED', 'Inscrit'), ('CONFIRMED', 'Confirme'), ('WAITLISTED', "Liste d'attente"), ('DECLINED', 'Refuse'), ('ATTENDED', 'Present'), ('ABSENT', 'Absent'), ('CANCELLED', 'Annule')], default='INVITED', max_length=24)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Paye'), ('CANCELLED', 'Annule')], default='PENDING', max_length=24)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_orders', to='events.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_orders', to='events.eventparticipant')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_ticket_order', to='payments.payment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket_orders', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('function', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_event_participants', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ticket_types', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('qr_code', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserve'), ('CONFIRMED', 'Confirme'), ('CHECKED_IN', 'Utilise'), ('CANCELLED', 'Annule')], default='RESERVED', max_length=24)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_event_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.ticketorder')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.eventparticipant')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.eventtickettype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tickets', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('contact', models.CharField(blank=True, max_length=180)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('function', models.CharField(blank=True, max_length=120)),
                ('organization', models.CharField(blank=True, max_length=180)),
                ('biography', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='event-speakers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_speakers', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('speaker', models.CharField(blank=True, max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedule_items', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventRevenueAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_revenue_id', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_at', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_allocations', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_revenue_allocations', to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='external_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participations', to='events.externalparticipant'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='members.member'),
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='EventOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EVENT_MANAGER', 'Responsable evenement'), ('CHECKIN_MANAGER', 'Responsable check-in'), ('FINANCE_MANAGER', 'Responsable finance'), ('COMMUNICATION_MANAGER', 'Communication'), ('OBSERVER', 'Observateur')], default='OBSERVER', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizer_roles', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_organizers', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('satisfaction', models.PositiveSmallIntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='events.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='events.eventparticipant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_feedback', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventExpenseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_expense_id', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('spent_at', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_allocations', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_expense_allocations', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(blank=True, upload_to='event-documents/')),
                ('document_type', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_documents', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('channels', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_announcements', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['workspace', 'event'], name='events_tick_workspa_4b8ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['workspace', 'status'], name='events_tick_workspa_061eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketorder',
            index=models.Index(fields=['reference'], name='events_tick_referen_be2de7_idx'),
        ),
        migrations.AddIndex(
            model_name='externalparticipant',
            index=models.Index(fields=['workspace', 'email'], name='events_exte_workspa_481b65_idx'),
        ),
        migrations.AddIndex(
            model_name='externalparticipant',
            index=models.Index(fields=['workspace', 'phone'], name='events_exte_workspa_ccdeae_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtickettype',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_ffd6df_idx'),
        ),
        migrations.AddIndex(
            model_name='eventtickettype',
            index=models.Index(fields=['workspace', 'is_active'], name='events_even_workspa_d0e89c_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventtickettype',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='uniq_event_ticket_type_name'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_1b4104_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['workspace', 'code'], name='events_even_workspa_aad033_idx'),
        ),
        migrations.AddIndex(
            model_name='eventticket',
            index=models.Index(fields=['workspace', 'status'], name='events_even_workspa_a83159_idx'),
        ),
        migrations.AddIndex(
            model_name='eventsponsor',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_36f400_idx'),
        ),
        migrations.AddIndex(
            model_name='eventspeaker',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_bfafd9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventscheduleitem',
            index=models.Index(fields=['workspace', 'event', 'start_time'], name='events_even_workspa_d99d44_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrevenueallocation',
            index=models.Index(fields=['workspace', 'event', 'received_at'], name='events_even_workspa_828cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='eventrevenueallocation',
            index=models.Index(fields=['workspace', 'external_revenue_id'], name='events_even_workspa_30f490_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['workspace', 'event', 'status'], name='events_even_workspa_e13cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['workspace', 'member'], name='events_even_workspa_2934b0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['workspace', 'external_participant'], name='events_even_workspa_eb8b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['workspace', 'qr_code'], name='events_even_workspa_ad6652_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='uniq_event_member_participant'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_38b2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['workspace', 'member'], name='events_even_workspa_e23560_idx'),
        ),
        migrations.AddIndex(
            model_name='eventorganizer',
            index=models.Index(fields=['workspace', 'role'], name='events_even_workspa_cbaabc_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventorganizer',
            constraint=models.UniqueConstraint(fields=('event', 'member'), name='uniq_event_organizer_member'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['workspace', 'event'], name='events_even_workspa_10d40f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventfeedback',
            index=models.Index(fields=['workspace', 'rating'], name='events_even_workspa_c3d6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='eventexpenseallocation',
            index=models.Index(fields=['workspace', 'event', 'spent_at'], name='events_even_workspa_f59883_idx'),
        ),
        migrations.AddIndex(
            model_name='eventexpenseallocation',
            index=models.Index(fields=['workspace', 'external_expense_id'], name='events_even_workspa_b03547_idx'),
        ),
        migrations.AddIndex(
            model_name='eventdocument',
            index=models.Index(fields=['workspace', 'event', '-created_at'], name='events_even_workspa_eb6461_idx'),
        ),
        migrations.AddIndex(
            model_name='eventannouncement',
            index=models.Index(fields=['workspace', 'event', '-created_at'], name='events_even_workspa_9f0c2b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventactivity',
            index=models.Index(fields=['workspace', 'event', '-created_at'], name='events_even_workspa_2f05bc_idx'),
        ),
        migrations.AddIndex(
            model_name='eventactivity',
            index=models.Index(fields=['action', '-created_at'], name='events_even_action_463a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'code'], name='events_even_workspa_388bab_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'start_at'], name='events_even_workspa_575184_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'end_at'], name='events_even_workspa_e277f7_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'status'], name='events_even_workspa_b32d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'event_type'], name='events_even_workspa_10e109_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'owner'], name='events_even_workspa_1117cb_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', 'project'], name='events_even_workspa_a61a77_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='uniq_event_workspace_code'),
        ),
    ]
