# Generated by Django 4.2.27 on 2026-08-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publie'), ('PLANNED', 'Planifie'), ('REGISTRATION_OPEN', 'Inscriptions ouvertes'), ('REGISTRATION_CLOSED', 'Inscriptions fermees'), ('ONGOING', 'En cours'), ('COMPLETED', 'Termine'), ('CANCELLED', 'Annule'), ('POSTPONED', 'Reporte'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=24),
        ),
    ]
