# Generated by Django 4.2.27 on 2026-08-30 09:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '__first__'),
        ('projects', '__first__'),
        ('payments', '0002_financialadjustment_paymentdocument_and_more'),
        ('workspaces', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='events.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INCOME_CATEGORY', 'Categorie recette'), ('EXPENSE_CATEGORY', 'Categorie depense')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_categories', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Recette'), ('EXPENSE', 'Depense')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('description', models.CharField(max_length=220)),
                ('reference', models.CharField(max_length=120)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente'), ('VALIDATED', 'Validee'), ('CANCELLED', 'Annulee')], default='VALIDATED', max_length=16)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('CONTRIBUTION', 'Cotisation'), ('PAYMENT', 'Paiement'), ('DONATION', 'Don'), ('EVENT', 'Evenement'), ('PROJECT', 'Projet'), ('OTHER', 'Autre')], default='MANUAL', max_length=24)),
                ('supplier_name', models.CharField(blank=True, max_length=160)),
                ('supplier_phone', models.CharField(blank=True, max_length=32)),
                ('invoice_reference', models.CharField(blank=True, max_length=120)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Especes'), ('MOBILE_MONEY', 'Mobile Money'), ('BANK_TRANSFER', 'Virement'), ('CARD', 'Carte'), ('OTHER', 'Autre')], max_length=24)),
                ('requires_receipt', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialcategory')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_transactions', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='events.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='projects.project')),
                ('source_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transaction', to='payments.payment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_expense_receipt', models.BooleanField(default=False)),
                ('expense_validation_threshold', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), max_digits=14)),
                ('large_expense_threshold', models.DecimalField(decimal_places=2, default=Decimal('250000.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_settings', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('CLOSED', 'Cloturee')], default='OPEN', max_length=16)),
                ('closing_summary', models.JSONField(blank=True, default=dict)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='finance_fis_workspa_b319a3_idx'), models.Index(fields=['workspace', 'start_date', 'end_date'], name='finance_fis_workspa_11c41c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransactionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='financial-documents/')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Facture'), ('RECEIPT', 'Recu'), ('VOUCHER', 'Bon'), ('PHOTO', 'Photo'), ('PDF', 'PDF'), ('OTHER', 'Autre')], default='RECEIPT', max_length=24)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='finance.financialtransaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_documents', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'transaction', '-created_at'], name='finance_fin_workspa_eb745d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'transaction_date'], name='finance_fin_workspa_180ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'transaction_type'], name='finance_fin_workspa_5ea600_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'category'], name='finance_fin_workspa_eeeedb_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'status'], name='finance_fin_workspa_7150a6_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'source'], name='finance_fin_workspa_fc6977_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'project'], name='finance_fin_workspa_d049e7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'event'], name='finance_fin_workspa_8747f1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'created_at'], name='finance_fin_workspa_34da8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialtransaction',
            constraint=models.UniqueConstraint(fields=('workspace', 'reference'), name='uniq_finance_transaction_workspace_reference'),
        ),
        migrations.AddIndex(
            model_name='financialcategory',
            index=models.Index(fields=['workspace', 'kind', 'is_active'], name='finance_fin_workspa_7f0046_idx'),
        ),
        migrations.AddIndex(
            model_name='financialcategory',
            index=models.Index(fields=['workspace', 'name'], name='finance_fin_workspa_0ba75a_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialcategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'kind', 'name'), name='uniq_finance_category_workspace_kind_name'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['workspace', 'is_active'], name='finance_cos_workspa_490fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['workspace', 'project'], name='finance_cos_workspa_ef4ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['workspace', 'event'], name='finance_cos_workspa_1838b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_cost_center_workspace_name'),
        ),
    ]
