# Generated by Django 4.2.27 on 2026-09-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_membership_onboarding'),
        ('finance', '0002_add_rejected_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='members.member'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='sender_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='sender_type',
            field=models.CharField(choices=[('MEMBER', 'Membre'), ('OTHER', 'Autre')], default='OTHER', max_length=16),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('CONTRIBUTION', 'Cotisation'), ('PAYMENT', 'Paiement'), ('DONATION', 'Don'), ('GRANT', 'Subvention'), ('SPONSORSHIP', 'Sponsoring'), ('EVENT', 'Evenement'), ('PROJECT', 'Projet'), ('OTHER', 'Autre')], default='MANUAL', max_length=24),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['workspace', 'member'], name='finance_fin_workspa_478228_idx'),
        ),
    ]
