# Generated by Codex on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="plan",
            name="currency",
            field=models.CharField(default="XOF", max_length=3),
        ),
        migrations.AddField(
            model_name="plan",
            name="billing_period",
            field=models.CharField(default="month", max_length=24),
        ),
    ]
