# Generated by Django 4.2.27 on 2026-08-30 10:36

import apps.budgets.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '__first__'),
        ('finance', '0001_initial'),
        ('workspaces', '__first__'),
        ('events', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Mensuel'), ('QUARTERLY', 'Trimestriel'), ('SEMIANNUAL', 'Semestriel'), ('ANNUAL', 'Annuel'), ('CUSTOM', 'Personnalise')], default='ANNUAL', max_length=16)),
                ('scope_type', models.CharField(choices=[('WORKSPACE', 'Association'), ('PROJECT', 'Projet'), ('EVENT', 'Evenement')], default='WORKSPACE', max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('PAUSED', 'En pause'), ('CLOSED', 'Cloture'), ('ARCHIVED', 'Archive')], default='DRAFT', max_length=16)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_budgets', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_budgets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='events.event')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='projects.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_over_budget_expense', models.BooleanField(default=True)),
                ('thresholds', models.JSONField(blank=True, default=apps.budgets.models.default_budget_thresholds)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_whatsapp', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_settings', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('committed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budgets.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.financialcategory')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manual', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='budgets.budget')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='budgets.budgetline')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignment', to='finance.financialtransaction')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_assignments', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('budget.threshold_reached', 'Seuil atteint'), ('budget.nearly_exceeded', 'Presque depasse'), ('budget.exceeded', 'Depasse')], max_length=64)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Alerte'), ('CRITICAL', 'Critique')], default='INFO', max_length=16)),
                ('threshold_percent', models.PositiveSmallIntegerField(default=0)),
                ('current_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('message', models.CharField(max_length=255)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budget')),
                ('budget_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budgets.budgetline')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_alerts', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='budgets.budget')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['workspace', 'budget'], name='budgets_bud_workspa_e24884_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['workspace', 'category'], name='budgets_bud_workspa_722a49_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetline',
            index=models.Index(fields=['workspace', 'is_active'], name='budgets_bud_workspa_d200c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='uniq_budget_line_category'),
        ),
        migrations.AddIndex(
            model_name='budgetassignment',
            index=models.Index(fields=['workspace', 'budget'], name='budgets_bud_workspa_586c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetassignment',
            index=models.Index(fields=['workspace', 'budget_line'], name='budgets_bud_workspa_5eb9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetassignment',
            index=models.Index(fields=['workspace', 'transaction'], name='budgets_bud_workspa_c09f40_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['workspace', 'budget', 'is_resolved'], name='budgets_bud_workspa_7e5b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['workspace', 'severity', '-created_at'], name='budgets_bud_workspa_38fd43_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='budgets_bud_alert_t_2ae80a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetactivity',
            index=models.Index(fields=['workspace', 'budget', '-created_at'], name='budgets_bud_workspa_d5576b_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetactivity',
            index=models.Index(fields=['action', '-created_at'], name='budgets_bud_action_a23f65_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'status'], name='budgets_bud_workspa_7bc97f_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'scope_type'], name='budgets_bud_workspa_016147_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'start_date', 'end_date'], name='budgets_bud_workspa_e5bced_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'project'], name='budgets_bud_workspa_93c74a_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'event'], name='budgets_bud_workspa_8a601d_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['workspace', 'created_at'], name='budgets_bud_workspa_d5b832_idx'),
        ),
    ]
