# Generated by Django 4.2.27 on 2026-08-29 17:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '__first__'),
        ('workspaces', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('contribution_type', models.CharField(choices=[('MEMBERSHIP', 'Adhesion'), ('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('YEARLY', 'Annuelle'), ('SPECIAL', 'Speciale'), ('EVENT', 'Evenementielle'), ('PROJECT', 'Projet'), ('OTHER', 'Autre')], default='MONTHLY', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('periodicity', models.CharField(choices=[('ONE_TIME', 'Ponctuelle'), ('MONTHLY', 'Mensuelle'), ('QUARTERLY', 'Trimestrielle'), ('YEARLY', 'Annuelle'), ('CUSTOM', 'Personnalisee')], default='MONTHLY', max_length=24)),
                ('period_label', models.CharField(blank=True, max_length=120)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('target_mode', models.CharField(choices=[('ALL_ACTIVE', 'Tous les membres actifs'), ('CATEGORY', 'Categorie'), ('SELECTED', 'Selection'), ('SEGMENT', 'Segment')], default='ALL_ACTIVE', max_length=24)),
                ('target_segment', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Active'), ('PAUSED', 'En pause'), ('CLOSED', 'Cloturee'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membercategory')),
                ('target_members', models.ManyToManyField(blank=True, related_name='targeted_contribution_campaigns', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_campaigns', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('days_from_due_date', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('channel', models.CharField(default='notification', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_reminder_rules', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionCategoryAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_amounts', to='contributions.contributioncampaign')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.membercategory')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PARTIALLY_PAID', 'Partiellement payee'), ('PAID', 'Payee'), ('OVERDUE', 'En retard'), ('CANCELLED', 'Annulee'), ('WAIVED', 'Exoneree')], default='PENDING', max_length=24)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='contributions.contributioncampaign')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='contributioncategoryamount',
            constraint=models.UniqueConstraint(fields=('campaign', 'category'), name='uniq_campaign_category_amount'),
        ),
        migrations.AddIndex(
            model_name='contributioncampaign',
            index=models.Index(fields=['workspace', 'status'], name='contributio_workspa_ede9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='contributioncampaign',
            index=models.Index(fields=['workspace', 'due_date'], name='contributio_workspa_75de9a_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['workspace', 'status'], name='contributio_workspa_9b2612_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['workspace', 'due_date'], name='contributio_workspa_8b795e_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['workspace', 'member'], name='contributio_workspa_d60153_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['workspace', 'campaign'], name='contributio_workspa_ea4a01_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['workspace', 'created_at'], name='contributio_workspa_e9e9f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('campaign', 'member'), name='uniq_contribution_campaign_member'),
        ),
    ]
