# Generated by Django 4.2.27 on 2026-08-29 17:32

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '__first__'),
        ('workspaces', '__first__'),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRecoverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_goal_percent', models.DecimalField(decimal_places=2, default=Decimal('90.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_recovery_settings', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('EXCEL', 'Excel'), ('PDF', 'PDF')], default='CSV', max_length=16)),
                ('export_type', models.CharField(default='recovery', max_length=40)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('file', models.FileField(blank=True, upload_to='contribution-exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_export_requests', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ContributionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_kind', models.CharField(choices=[('REMINDER', 'Rappel'), ('OVERDUE', 'Relance retard'), ('FINAL_NOTICE', 'Dernier avis')], default='REMINDER', max_length=24)),
                ('channel', models.CharField(choices=[('IN_APP', 'NOVEX'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=24)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUEUED', 'En file'), ('SENT', 'Envoyee'), ('FAILED', 'Echec'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=24)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contributions.contributioncampaign')),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contributions.contribution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contribution_reminders', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_reminders', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'status'], name='contributio_workspa_7bd368_idx'), models.Index(fields=['workspace', 'channel'], name='contributio_workspa_a6e7d6_idx'), models.Index(fields=['workspace', 'scheduled_for'], name='contributio_workspa_f341be_idx'), models.Index(fields=['workspace', 'contribution'], name='contributio_workspa_38bafb_idx'), models.Index(fields=['workspace', 'member'], name='contributio_workspa_32eb3a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='contributionreminder',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workspace', 'idempotency_key'), name='uniq_contribution_reminder_idempotency'),
        ),
        migrations.AddIndex(
            model_name='contributionexportrequest',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='contributio_workspa_3c07f0_idx'),
        ),
    ]
