# Generated by Django 4.2.27 on 2026-08-31 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_country_code', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('function', models.CharField(default='Membre', max_length=120)),
                ('gender', models.CharField(choices=[('female', 'Femme'), ('male', 'Homme'), ('other', 'Autre'), ('unspecified', 'Non precise')], default='unspecified', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=160)),
                ('photo', models.ImageField(blank=True, upload_to='members/')),
                ('join_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('pending', 'En attente'), ('suspended', 'Suspendu'), ('resigned', 'Demissionnaire'), ('excluded', 'Exclu'), ('deceased', 'Decede'), ('former', 'Ancien'), ('archived', 'Archive')], default='active', max_length=24)),
                ('suspension_reason', models.TextField(blank=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemberGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, related_name='groups', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_groups', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('date', 'Date'), ('boolean', 'Booleen'), ('select', 'Selection'), ('multi_select', 'Selection multiple')], default='text', max_length=24)),
                ('is_required', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_custom_field_definitions', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_categories', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.membercategory'),
        ),
        migrations.AddField(
            model_name='member',
            name='linked_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='member',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_members', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='MemberTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(default='#0f7ff2', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='tags', to='members.member')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_tags', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'name'], name='members_mem_workspa_f48042_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membertag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_member_tag_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='membergroup',
            index=models.Index(fields=['workspace', 'name'], name='members_mem_workspa_54fae4_idx'),
        ),
        migrations.AddConstraint(
            model_name='membergroup',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_member_group_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='membercustomfielddefinition',
            index=models.Index(fields=['workspace', 'name'], name='members_mem_workspa_db3222_idx'),
        ),
        migrations.AddIndex(
            model_name='membercustomfielddefinition',
            index=models.Index(fields=['workspace', 'field_type'], name='members_mem_workspa_4fd67f_idx'),
        ),
        migrations.AddConstraint(
            model_name='membercustomfielddefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_member_custom_field_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='membercategory',
            index=models.Index(fields=['workspace', 'name'], name='members_mem_workspa_24eaaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='membercategory',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_member_category_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['workspace', '-created_at'], name='members_mem_workspa_f20954_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['member', '-created_at'], name='members_mem_member__4d1b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['action', '-created_at'], name='members_mem_action_567628_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'status'], name='members_mem_workspa_90322c_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'created_at'], name='members_mem_workspa_aab44a_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'phone'], name='members_mem_workspa_eed5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'email'], name='members_mem_workspa_421667_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'membership_number'], name='members_mem_workspa_218ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'last_name'], name='members_mem_workspa_f0e1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'join_date'], name='members_mem_workspa_517ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['workspace', 'function'], name='members_mem_workspa_dcee5c_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('workspace', 'membership_number'), name='uniq_member_number_per_workspace'),
        ),
    ]
