# Generated by Codex on 2026-08-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("workspaces", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("membership_enabled", models.BooleanField(default=True)),
                ("public_form_enabled", models.BooleanField(default=False)),
                ("invitation_enabled", models.BooleanField(default=True)),
                ("approval_required", models.BooleanField(default=True)),
                ("auto_activate_members", models.BooleanField(default=True)),
                ("public_title", models.CharField(default="Rejoindre l'association", max_length=180)),
                ("public_description", models.TextField(blank=True)),
                ("welcome_message", models.TextField(blank=True)),
                ("confirmation_message", models.TextField(default="Votre demande a bien ete envoyee.")),
                ("visible_fields", models.JSONField(blank=True, default=list)),
                ("required_fields", models.JSONField(blank=True, default=list)),
                ("invitation_expiration_days", models.PositiveSmallIntegerField(default=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("workspace", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="membership_settings", to="workspaces.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="MembershipApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("photo", models.ImageField(blank=True, upload_to="membership-applications/")),
                ("occupation", models.CharField(blank=True, max_length=160)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("internal_note", models.TextField(blank=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("duplicate_warning", models.JSONField(blank=True, default=dict)),
                ("source", models.CharField(choices=[("public_form", "Formulaire public"), ("admin", "Saisie admin"), ("invitation", "Invitation")], default="admin", max_length=24)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("under_review", "En cours"), ("approved", "Approuvee"), ("rejected", "Refusee"), ("cancelled", "Annulee"), ("expired", "Expiree")], default="pending", max_length=24)),
                ("submitted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="membership_applications", to=settings.AUTH_USER_MODEL)),
                ("member", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="membership_applications", to="members.member")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_membership_applications", to=settings.AUTH_USER_MODEL)),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="membership_applications", to="workspaces.workspace")),
            ],
        ),
        migrations.CreateModel(
            name="MemberInvitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("function", models.CharField(default="Membre", max_length=120)),
                ("message", models.TextField(blank=True)),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("status", models.CharField(choices=[("pending", "En attente"), ("accepted", "Acceptee"), ("declined", "Refusee"), ("cancelled", "Annulee"), ("expired", "Expiree")], default="pending", max_length=20)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("declined_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accepted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="accepted_member_invitations", to=settings.AUTH_USER_MODEL)),
                ("invited_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sent_member_invitations", to=settings.AUTH_USER_MODEL)),
                ("member", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="invitations", to="members.member")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="member_invitations", to="workspaces.workspace")),
            ],
        ),
        migrations.AddIndex(model_name="membershipapplication", index=models.Index(fields=["workspace", "status"], name="members_mem_workspa_058d21_idx")),
        migrations.AddIndex(model_name="membershipapplication", index=models.Index(fields=["workspace", "-submitted_at"], name="members_mem_workspa_ef8840_idx")),
        migrations.AddIndex(model_name="membershipapplication", index=models.Index(fields=["workspace", "email"], name="members_mem_workspa_719c80_idx")),
        migrations.AddIndex(model_name="membershipapplication", index=models.Index(fields=["workspace", "phone"], name="members_mem_workspa_9e50f0_idx")),
        migrations.AddIndex(model_name="memberinvitation", index=models.Index(fields=["workspace", "status"], name="members_mem_workspa_042189_idx")),
        migrations.AddIndex(model_name="memberinvitation", index=models.Index(fields=["workspace", "email"], name="members_mem_workspa_5237e4_idx")),
        migrations.AddIndex(model_name="memberinvitation", index=models.Index(fields=["workspace", "phone"], name="members_mem_workspa_1f71b0_idx")),
        migrations.AddIndex(model_name="memberinvitation", index=models.Index(fields=["token_hash"], name="members_mem_token_h_541478_idx")),
        migrations.AddIndex(model_name="memberinvitation", index=models.Index(fields=["expires_at"], name="members_mem_expires_e2897b_idx")),
    ]
