# Generated by Django 4.2.27 on 2026-08-30 12:25

import apps.documents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('payments', '0002_financialadjustment_paymentdocument_and_more'),
        ('members', '__first__'),
        ('workspaces', '__first__'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to=apps.documents.models.secure_document_upload_path)),
                ('file_type', models.CharField(max_length=24)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('administrative', 'Administratif'), ('financial', 'Financier'), ('members', 'Membres'), ('contributions', 'Cotisations'), ('project', 'Projet'), ('event', 'Evenement'), ('legal', 'Juridique'), ('report', 'Rapport'), ('communication', 'Communication'), ('other', 'Autre')], default='other', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('active', 'Actif'), ('approved', 'Approuve'), ('rejected', 'Rejete'), ('archived', 'Archive'), ('trash', 'Corbeille')], default='active', max_length=24)),
                ('visibility', models.CharField(choices=[('private', 'Prive'), ('members', 'Membres'), ('team', 'Equipe'), ('workspace', 'Workspace'), ('shared', 'Partage')], default='private', max_length=24)),
                ('sensitivity', models.CharField(choices=[('normal', 'Normal'), ('sensitive', 'Sensible')], default='normal', max_length=24)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='events.event')),
                ('financial_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='finance.financialtransaction')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_tags', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.documents.models.secure_share_token, max_length=96, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=160)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='documents.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_share_links', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('member', 'Membre'), ('role', 'Role'), ('team', 'Equipe')], max_length=16)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('can_view', models.BooleanField(default=True)),
                ('can_download', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_share', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='members.member')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='workspaces.role')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=24)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.documentfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_folders', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favorites', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_favorites', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente'), ('approved', 'Approuve'), ('rejected', 'Rejete')], default='pending', max_length=24)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documents.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_approvals', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('document.created', 'Document cree'), ('document.updated', 'Document modifie'), ('document.downloaded', 'Document telecharge'), ('document.shared', 'Document partage'), ('document.unshared', 'Document de-partage'), ('document.archived', 'Document archive'), ('document.restored', 'Document restaure'), ('document.deleted', 'Document supprime'), ('document.permanently_deleted', 'Document supprime definitivement'), ('document.version_created', 'Version creee'), ('document.version_restored', 'Version restauree'), ('document.approved', 'Document approuve'), ('document.rejected', 'Document rejete')], max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.document')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='documents.documentfolder')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_activities', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_access_logs', to='workspaces.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentfolder'),
        ),
        migrations.AddField(
            model_name='document',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='members.member'),
        ),
        migrations.AddField(
            model_name='document',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='document',
            name='previous_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_documents', to='documents.documentfolder'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ged_documents', to='projects.project'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='documents.documenttag'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=apps.documents.models.secure_document_upload_path)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(max_length=24)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('change_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restore_versions', to='documents.documentversion')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'document', '-version_number'], name='documents_d_workspa_468a3c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_document_version_number'),
        ),
        migrations.AddIndex(
            model_name='documenttag',
            index=models.Index(fields=['workspace', 'name'], name='documents_d_workspa_af67a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='documenttag',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_document_tag_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='documentsharelink',
            index=models.Index(fields=['workspace', 'document', 'is_active'], name='documents_d_workspa_abd764_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['workspace', 'document'], name='documents_d_workspa_871997_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['workspace', 'subject_type'], name='documents_d_workspa_538d73_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['workspace', 'parent'], name='documents_d_workspa_83b806_idx'),
        ),
        migrations.AddIndex(
            model_name='documentfolder',
            index=models.Index(fields=['workspace', 'is_archived'], name='documents_d_workspa_00420d_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfolder',
            constraint=models.UniqueConstraint(fields=('workspace', 'parent', 'name'), name='uniq_document_folder_workspace_parent_name'),
        ),
        migrations.AddIndex(
            model_name='documentfavorite',
            index=models.Index(fields=['workspace', 'user', '-created_at'], name='documents_d_workspa_ffe123_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentfavorite',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='uniq_document_favorite_user'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['workspace', 'document', 'status'], name='documents_d_workspa_a371d7_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['workspace', 'approver', 'status'], name='documents_d_workspa_1cb6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['workspace', 'document', '-created_at'], name='documents_d_workspa_1ed797_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['action', '-created_at'], name='documents_d_action_dec8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['workspace', 'document', '-created_at'], name='documents_d_workspa_b35f27_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['workspace', 'actor', '-created_at'], name='documents_d_workspa_89484f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'status'], name='documents_d_workspa_9cf75b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'category'], name='documents_d_workspa_0e2b19_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'folder'], name='documents_d_workspa_b41578_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'visibility'], name='documents_d_workspa_8ea277_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'sensitivity'], name='documents_d_workspa_2c2540_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'project'], name='documents_d_workspa_4bb91b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'event'], name='documents_d_workspa_e1d0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'financial_transaction'], name='documents_d_workspa_9e8529_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'uploaded_by'], name='documents_d_workspa_9a60ca_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-updated_at'], name='documents_d_workspa_306e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-created_at'], name='documents_d_workspa_5cefbc_idx'),
        ),
    ]
