# Generated by Django 4.2.27 on 2026-08-30 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '__first__'),
        ('members', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('is_default', models.BooleanField(default=False)),
                ('layout', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_dashboards', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('report_type', models.CharField(choices=[('overview', "Vue d'ensemble"), ('finance', 'Finance'), ('members', 'Membres'), ('contributions', 'Cotisations'), ('projects', 'Projets'), ('events', 'Evenements'), ('documents', 'Documents'), ('activity', 'Activite'), ('performance', 'Performance'), ('annual', 'Annuel')], max_length=32)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('overview', "Vue d'ensemble"), ('finance', 'Finance'), ('members', 'Membres'), ('contributions', 'Cotisations'), ('projects', 'Projets'), ('events', 'Evenements'), ('documents', 'Documents'), ('activity', 'Activite'), ('performance', 'Performance'), ('annual', 'Annuel')], max_length=32)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=16)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En traitement'), ('completed', 'Termine'), ('failed', 'Echoue')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='report-exports/')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('saved_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='reports.savedreport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_export_requests', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('kpi', 'KPI'), ('chart', 'Graphique'), ('table', 'Table'), ('progress', 'Progression'), ('alert', 'Alerte')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('metric_key', models.CharField(blank=True, max_length=120)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.analyticsdashboard')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_widgets', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], max_length=16)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=16)),
                ('send_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reports.savedreport')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'is_active', 'next_run_at'], name='reports_sch_workspa_841216_idx'), models.Index(fields=['workspace', 'frequency'], name='reports_sch_workspa_e57348_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedReportShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('member', 'Membre'), ('role', 'Role'), ('team', 'Equipe')], max_length=16)),
                ('team', models.CharField(blank=True, max_length=120)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_shares', to='members.member')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='reports.savedreport')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_shares', to='workspaces.role')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_report_shares', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'report'], name='reports_sav_workspa_de8f64_idx'), models.Index(fields=['workspace', 'subject_type'], name='reports_sav_workspa_349b04_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['workspace', 'report_type'], name='reports_sav_workspa_6bb234_idx'),
        ),
        migrations.AddIndex(
            model_name='savedreport',
            index=models.Index(fields=['workspace', 'created_by', '-updated_at'], name='reports_sav_workspa_94d878_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['workspace', 'status', '-created_at'], name='reports_rep_workspa_ca50fb_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexportrequest',
            index=models.Index(fields=['workspace', 'report_type'], name='reports_rep_workspa_56fd52_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticswidget',
            index=models.Index(fields=['workspace', 'dashboard', 'is_visible'], name='reports_ana_workspa_1d6025_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticswidget',
            index=models.Index(fields=['workspace', 'widget_type'], name='reports_ana_workspa_128a44_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['workspace', 'is_default'], name='reports_ana_workspa_332f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdashboard',
            index=models.Index(fields=['workspace', 'created_by'], name='reports_ana_workspa_9a43af_idx'),
        ),
    ]
