# Generated by Django 4.2.27 on 2026-08-29 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '__first__'),
        ('contributions', '0002_contributionrecoverysettings_and_more'),
        ('members', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('novex_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('provider', models.CharField(default='manual', max_length=64)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=160)),
                ('checkout_url', models.URLField(blank=True)),
                ('idempotency_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'Traitement'), ('SUCCESS', 'Reussi'), ('FAILED', 'Echoue'), ('CANCELLED', 'Annule'), ('EXPIRED', 'Expire'), ('REFUNDED', 'Rembourse'), ('PARTIALLY_REFUNDED', 'Partiellement rembourse')], default='PENDING', max_length=24)),
                ('payment_method', models.CharField(choices=[('MANUAL', 'Manuel'), ('CASH', 'Especes'), ('CHECK', 'Cheque'), ('OTHER', 'Autre'), ('EXTERNAL_MOBILE_MONEY', 'Mobile Money externe'), ('MOBILE_MONEY', 'Mobile Money'), ('CARD', 'Carte bancaire'), ('AGGREGATOR', 'Agregateur'), ('BANK_TRANSFER', 'Virement')], default='MANUAL', max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('payment.initialized', 'Initialise'), ('payment.processing', 'Traitement'), ('payment.succeeded', 'Reussi'), ('payment.failed', 'Echoue'), ('payment.cancelled', 'Annule'), ('payment.expired', 'Expire'), ('payment.refunded', 'Rembourse'), ('payment.webhook_received', 'Webhook recu'), ('payment.webhook_rejected', 'Webhook rejete')], max_length=80)),
                ('from_status', models.CharField(blank=True, max_length=24)),
                ('to_status', models.CharField(blank=True, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('event_id', models.CharField(max_length=160)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('verification_token_hash', models.CharField(blank=True, max_length=160)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='receipts/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='workspaces.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_payment_webhook_event'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='members.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['workspace', 'payment', '-created_at'], name='payments_pa_workspa_4c0aba_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['event_type', '-created_at'], name='payments_pa_event_t_c8502b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'status'], name='payments_pa_workspa_6e738e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'created_at'], name='payments_pa_workspa_25a4d3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'member'], name='payments_pa_workspa_a23805_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'contribution'], name='payments_pa_workspa_9760ce_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'reference'], name='payments_pa_workspa_e34d35_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_transaction_id'], name='payments_pa_provide_26ee43_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='uniq_payment_workspace_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), fields=('provider', 'provider_transaction_id'), name='uniq_payment_provider_transaction'),
        ),
    ]
