# Generated by Django 4.2.27 on 2026-08-29 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '__first__'),
        ('workspaces', '__first__'),
        ('contributions', '0002_contributionrecoverysettings_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Entree'), ('OUT', 'Sortie')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XOF', max_length=3)),
                ('reason', models.TextField()),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('POSTED', 'Comptabilise'), ('CANCELLED', 'Annule')], default='POSTED', max_length=24)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('file', models.FileField(upload_to='payment-documents/')),
                ('document_type', models.CharField(choices=[('RECEIPT', 'Recu'), ('PROOF_OF_PAYMENT', 'Preuve de paiement'), ('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY_PROOF', 'Preuve Mobile Money'), ('OTHER', 'Autre')], default='PROOF_OF_PAYMENT', max_length=32)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('scan_status', models.CharField(choices=[('NOT_CONFIGURED', 'Scan non configure'), ('PENDING', 'Scan en attente'), ('CLEAN', 'Fichier sain'), ('INFECTED', 'Fichier infecte')], default='NOT_CONFIGURED', max_length=24)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='reconciliation_status',
            field=models.CharField(choices=[('UNMATCHED', 'Non rapproche'), ('MATCHED', 'Rapproche'), ('REVIEW_REQUIRED', 'Revue requise')], default='UNMATCHED', max_length=24),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='receipt',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='currency',
            field=models.CharField(default='XOF', max_length=3),
        ),
        migrations.AddField(
            model_name='receipt',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='members.member'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Genere'), ('SENT', 'Envoye'), ('CANCELLED', 'Annule')], default='GENERATED', max_length=24),
        ),
        migrations.AddField(
            model_name='receipt',
            name='storage_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentevent',
            name='event_type',
            field=models.CharField(choices=[('payment.initialized', 'Initialise'), ('payment.processing', 'Traitement'), ('payment.succeeded', 'Reussi'), ('payment.failed', 'Echoue'), ('payment.cancelled', 'Annule'), ('payment.expired', 'Expire'), ('payment.refunded', 'Rembourse'), ('payment.webhook_received', 'Webhook recu'), ('payment.webhook_rejected', 'Webhook rejete'), ('payment.refund_requested', 'Remboursement demande'), ('receipt.created', 'Recu cree'), ('receipt.generated', 'Recu genere'), ('receipt.downloaded', 'Recu telecharge'), ('receipt.sent', 'Recu envoye'), ('payment_document.uploaded', 'Justificatif ajoute'), ('payment_document.deleted', 'Justificatif supprime'), ('financial_adjustment.created', 'Ajustement financier cree')], max_length=80),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['workspace', 'reconciliation_status'], name='payments_pa_workspa_ab564d_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['workspace', 'member', '-issued_at'], name='payments_re_workspa_7c720a_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['workspace', 'receipt_number'], name='payments_re_workspa_37cef4_idx'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_documents', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='contributions.contribution'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_adjustments', to='members.member'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_adjustments', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['workspace', 'payment', '-created_at'], name='payments_pa_workspa_87cebe_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentdocument',
            index=models.Index(fields=['document_type', '-created_at'], name='payments_pa_documen_8172c1_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['workspace', '-created_at'], name='payments_fi_workspa_c34ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['workspace', 'status'], name='payments_fi_workspa_99f670_idx'),
        ),
    ]
