# Generated by Codex on 2026-09-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
        ("payments", "0002_financialadjustment_paymentdocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="member",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="members.member"),
        ),
    ]
