# Generated by Django 4.2.27 on 2026-08-31 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
        ('members', '0002_membership_onboarding'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('ANNOUNCEMENT', 'Annonce'), ('BROADCAST', 'Message collectif'), ('DIRECT_NOTIFICATION', 'Notification directe'), ('SYSTEM_NOTIFICATION', 'Notification systeme')], default='BROADCAST', max_length=32)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Evenement'), ('FINANCE', 'Finance'), ('ADMINISTRATION', 'Administration'), ('DOCUMENT', 'Document'), ('SECURITY', 'Securite'), ('SYSTEM', 'Systeme')], default='GENERAL', max_length=32)),
                ('priority', models.CharField(choices=[('LOW', 'Faible'), ('NORMAL', 'Normale'), ('HIGH', 'Haute'), ('URGENT', 'Urgente')], default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SCHEDULED', 'Programmee'), ('PROCESSING', 'En cours'), ('SENT', 'Envoyee'), ('PARTIALLY_SENT', 'Partiellement envoyee'), ('FAILED', 'Echec'), ('CANCELLED', 'Annulee')], default='DRAFT', max_length=24)),
                ('audience_type', models.CharField(choices=[('ALL_MEMBERS', 'Tous les membres'), ('ACTIVE_MEMBERS', 'Membres actifs'), ('CATEGORY', 'Categorie'), ('FUNCTION', 'Fonction'), ('SEGMENT', 'Segment'), ('SELECTED_MEMBERS', 'Membres selectionnes')], default='ACTIVE_MEMBERS', max_length=32)),
                ('audience_filters', models.JSONField(blank=True, default=dict)),
                ('audience_snapshot', models.JSONField(blank=True, default=dict)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('deep_link', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('provider_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='communications', to='documents.document')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communications', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('PUSH', 'Push'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('SENT', 'Envoyee'), ('DELIVERED', 'Delivree'), ('READ', 'Lue'), ('FAILED', 'Echec')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.communication')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_recipients', to='members.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_recipients', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_recipients', to='workspaces.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Evenement'), ('FINANCE', 'Finance'), ('ADMINISTRATION', 'Administration'), ('DOCUMENT', 'Document'), ('SECURITY', 'Securite'), ('SYSTEM', 'Systeme')], default='GENERAL', max_length=32)),
                ('email_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('administrative_enabled', models.BooleanField(default=True)),
                ('marketing_enabled', models.BooleanField(default=False)),
                ('system_enabled', models.BooleanField(default=True)),
                ('security_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='members.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'member'], name='communicati_workspa_46c828_idx'), models.Index(fields=['workspace', 'user'], name='communicati_workspa_446d7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommunicationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('communication_type', models.CharField(choices=[('ANNOUNCEMENT', 'Annonce'), ('BROADCAST', 'Message collectif'), ('DIRECT_NOTIFICATION', 'Notification directe'), ('SYSTEM_NOTIFICATION', 'Notification systeme')], default='BROADCAST', max_length=32)),
                ('subject', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('EVENT', 'Evenement'), ('FINANCE', 'Finance'), ('ADMINISTRATION', 'Administration'), ('DOCUMENT', 'Document'), ('SECURITY', 'Securite'), ('SYSTEM', 'Systeme')], default='GENERAL', max_length=32)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_templates', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='communicati_workspa_5ab03c_idx'), models.Index(fields=['workspace', 'communication_type'], name='communicati_workspa_cf103b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='communicationtemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_communication_template_workspace_name'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['workspace', 'status'], name='communicati_workspa_16730e_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['workspace', 'channel', 'status'], name='communicati_workspa_63f1e1_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['workspace', 'member', '-created_at'], name='communicati_workspa_717e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['workspace', 'user', '-created_at'], name='communicati_workspa_8d983f_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['communication', 'status'], name='communicati_communi_8a185e_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationrecipient',
            constraint=models.UniqueConstraint(fields=('workspace', 'idempotency_key'), name='uniq_communication_recipient_idempotency'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['workspace', 'status'], name='communicati_workspa_e9a3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['workspace', 'communication_type'], name='communicati_workspa_ce4350_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['workspace', 'scheduled_at'], name='communicati_workspa_6f3667_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['workspace', '-created_at'], name='communicati_workspa_b15a34_idx'),
        ),
    ]
